name: susFS Builder

on:
  workflow_dispatch:

jobs:
  build:
    name: susFS Builder
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: NDK
        uses: nttld/setup-ndk@v1.5.0
        with:
          ndk-version: r27b

      - name: Clone susfs repo
        run: |
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b 1.3.8 susfs4ksu --depth=1
          cd susfs4ksu
          ls -lsa
    
      - name: Build
        run: |
          cd susfs4ksu
          echo "Building susfs tool"
          chmod +x ./build_ksu_susfs_tool.sh 
          ./build_ksu_susfs_tool.sh
          chmod +x ./build_ksu_module.sh
          ./build_ksu_module.sh

      - name: Upload arm64 Binary
        uses: actions/upload-artifact@v4
        with:
          name: bin64
          path: susfs4ksu/ksu_module_susfs/tools/ksu_susfs_arm64
          
      - name: Upload arm Binary
        uses: actions/upload-artifact@v4
        with:
          name: bin32
          path: susfs4ksu/ksu_module_susfs/tools/ksu_susfs_arm
          
      - name: Upload Module
        uses: actions/upload-artifact@v4
        with:
          name: module
          path: susfs4ksu/ksu_module_susfs.zip
